[[language]]
name = "rust"
scope = "source.rust"
file-types = ["rs"]
indent = { tab-width = 4, unit = "    " }
formatter = { command = "rustfmt", args = ["--config", "tab_spaces=4"] }
auto-format = true
roots = ["Cargo.toml", "Cargo.lock"]


[[language]]
name = "lua"
scope = "source.lua"
file-types = ["lua"]
indent = { tab-width = 2, unit = "  " }
auto-format = true


[[language]]
name = "python"
scope = "source.python"
file-types = ["py", "pyw", "pyi", "pyd", "pyc"]
comment-token = "#"
auto-format = true
language-servers = [ "basedpyright"] 
indent = { tab-width = 2, unit = "  " }
formatter = { command = "black", args = ["--quiet", "-"] }
roots = ["setup.cfg", "pyproject.toml", "requirements.txt", "Pipfile", "Pipfile.lock"]


[[language]]
name = "typescript"
scope = "source.ts"
file-types = ["ts", "tsx", "mts", "cts"]
auto-format = true
roots = ["tsconfig.json", "package.json",]


[[language]]
name = "javascript"
scope = "source.js"
file-types = ["js", "jsx", "mjs", "cjs"]
auto-format = true
roots = ["package.json"]


[[language]]
name = "json"
scope = "source.json"
file-types = ["json", "jsonc"]


[[language]]
name = "toml"
scope = "source.toml"
file-types = [ "toml" ] 

[[language]]
name = "kotlin"
scope = "source.kotlin"
file-types = [ "kt", "kts" ]
roots = ["build.gradle", "build.gradle.kts", "settings.gradle", "settings.gradle.kts"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
indent = { tab-width = 2, unit = "  " }
language-servers = ["kotlin-language-server"]
formatter = { command = "ktlint" }

[language-server.kotlin-language-server]
command = "kotlin-language-server"
